### PR TITLE
Update software table

### PR DESCRIPTION
**Pull request by RyanGutenkunst**
Addresses https://github.com/popsim-consortium/demes-paper/issues/57

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM!

**Comment by noscode** [comment]
LGTM too, thanks!

**Comment by molpopgen** [comment]
LGTM

**Review by apragsdale — APPROVED** [review]

**Comment by apragsdale** [comment]
Thanks @RyanGutenkunst, merging!

**Pull request merged**
