### PR TITLE
Cover letter draft

### PR DESCRIPTION
**Pull request by apragsdale**
Needs some work!

### CODE REVIEW

**Comment by grahamgower** [comment]
Oh cool, thanks @apragsdale! Any chance we could do this in latex as well though? Or Markdown? Downloading binary files is a bit more cumbersome than reading a diff.

Note also that I changed the title of the paper. Feel free to comment over in #13 if you have another suggestion.

**Comment by MattHartfield** [comment]
Draft looks good to me - my only comment is that it might be overkill to include references in it?

**Comment by apragsdale** [comment]
> Oh cool, thanks @apragsdale! Any chance we could do this in latex as well though? Or Markdown? Downloading binary files is a bit more cumbersome than reading a diff.
> 
> Note also that I changed the title of the paper. Feel free to comment over in #13 if you have another suggestion.

Not a problem -- switched to latex. Not sure why I had seen the old title.. updated that here.

> Draft looks good to me - my only comment is that it might be overkill to include references in it?

Agree it's a bit overkill.. I was trying to hint that this is a tool that links many widely used and well-cited software that were published by Genetics. Maybe that should just be said explicitly in the closing paragraph?

**Review by grahamgower — APPROVED** [review]
LGTM.

**Comment by MattHartfield** [comment]
> Agree it's a bit overkill.. I was trying to hint that this is a tool that links many widely used and well-cited software that were published by Genetics. Maybe that should just be said explicitly in the closing paragraph?

Yes I think that's a better solution.

**Comment by jeromekelleher** [comment]
Very very nice @apragsdale. I'd tweak a few bits here and there, but it's excellent.

**Comment by apragsdale** [comment]
> Very very nice @apragsdale. I'd tweak a few bits here and there, but it's excellent.

Thanks @jeromekelleher! I merged it pretty quickly, to move on to some other edits, but of course feel free to make some tweaks

**Pull request merged**
